/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model;


import com.example.jooq.model.tables.Customers;
import com.example.jooq.model.tables.Employees;
import com.example.jooq.model.tables.Offices;
import com.example.jooq.model.tables.Orderdetails;
import com.example.jooq.model.tables.Orders;
import com.example.jooq.model.tables.Payments;
import com.example.jooq.model.tables.Productlines;
import com.example.jooq.model.tables.Products;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>classicmodels</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_PRIMARY = Indexes0.CUSTOMERS_PRIMARY;
    public static final Index CUSTOMERS_SALESREPEMPLOYEENUMBER = Indexes0.CUSTOMERS_SALESREPEMPLOYEENUMBER;
    public static final Index EMPLOYEES_OFFICECODE = Indexes0.EMPLOYEES_OFFICECODE;
    public static final Index EMPLOYEES_PRIMARY = Indexes0.EMPLOYEES_PRIMARY;
    public static final Index EMPLOYEES_REPORTSTO = Indexes0.EMPLOYEES_REPORTSTO;
    public static final Index OFFICES_PRIMARY = Indexes0.OFFICES_PRIMARY;
    public static final Index ORDERDETAILS_PRIMARY = Indexes0.ORDERDETAILS_PRIMARY;
    public static final Index ORDERDETAILS_PRODUCTCODE = Indexes0.ORDERDETAILS_PRODUCTCODE;
    public static final Index ORDERS_CUSTOMERNUMBER = Indexes0.ORDERS_CUSTOMERNUMBER;
    public static final Index ORDERS_PRIMARY = Indexes0.ORDERS_PRIMARY;
    public static final Index PAYMENTS_PRIMARY = Indexes0.PAYMENTS_PRIMARY;
    public static final Index PRODUCTLINES_PRIMARY = Indexes0.PRODUCTLINES_PRIMARY;
    public static final Index PRODUCTS_PRIMARY = Indexes0.PRODUCTS_PRIMARY;
    public static final Index PRODUCTS_PRODUCTLINE = Indexes0.PRODUCTS_PRODUCTLINE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_PRIMARY = Internal.createIndex("PRIMARY", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.CUSTOMERNUMBER }, true);
        public static Index CUSTOMERS_SALESREPEMPLOYEENUMBER = Internal.createIndex("salesRepEmployeeNumber", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.SALESREPEMPLOYEENUMBER }, false);
        public static Index EMPLOYEES_OFFICECODE = Internal.createIndex("officeCode", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.OFFICECODE }, false);
        public static Index EMPLOYEES_PRIMARY = Internal.createIndex("PRIMARY", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.EMPLOYEENUMBER }, true);
        public static Index EMPLOYEES_REPORTSTO = Internal.createIndex("reportsTo", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.REPORTSTO }, false);
        public static Index OFFICES_PRIMARY = Internal.createIndex("PRIMARY", Offices.OFFICES, new OrderField[] { Offices.OFFICES.OFFICECODE }, true);
        public static Index ORDERDETAILS_PRIMARY = Internal.createIndex("PRIMARY", Orderdetails.ORDERDETAILS, new OrderField[] { Orderdetails.ORDERDETAILS.ORDERNUMBER, Orderdetails.ORDERDETAILS.PRODUCTCODE }, true);
        public static Index ORDERDETAILS_PRODUCTCODE = Internal.createIndex("productCode", Orderdetails.ORDERDETAILS, new OrderField[] { Orderdetails.ORDERDETAILS.PRODUCTCODE }, false);
        public static Index ORDERS_CUSTOMERNUMBER = Internal.createIndex("customerNumber", Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMERNUMBER }, false);
        public static Index ORDERS_PRIMARY = Internal.createIndex("PRIMARY", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDERNUMBER }, true);
        public static Index PAYMENTS_PRIMARY = Internal.createIndex("PRIMARY", Payments.PAYMENTS, new OrderField[] { Payments.PAYMENTS.CUSTOMERNUMBER, Payments.PAYMENTS.CHECKNUMBER }, true);
        public static Index PRODUCTLINES_PRIMARY = Internal.createIndex("PRIMARY", Productlines.PRODUCTLINES, new OrderField[] { Productlines.PRODUCTLINES.PRODUCTLINE }, true);
        public static Index PRODUCTS_PRIMARY = Internal.createIndex("PRIMARY", Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.PRODUCTCODE }, true);
        public static Index PRODUCTS_PRODUCTLINE = Internal.createIndex("productLine", Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.PRODUCTLINE }, false);
    }
}
