/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model;


import com.example.jooq.model.tables.Customers;
import com.example.jooq.model.tables.Employees;
import com.example.jooq.model.tables.Offices;
import com.example.jooq.model.tables.Orderdetails;
import com.example.jooq.model.tables.Orders;
import com.example.jooq.model.tables.Payments;
import com.example.jooq.model.tables.Productlines;
import com.example.jooq.model.tables.Products;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in classicmodels
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>classicmodels.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>classicmodels.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>classicmodels.offices</code>.
     */
    public static final Offices OFFICES = Offices.OFFICES;

    /**
     * The table <code>classicmodels.orderdetails</code>.
     */
    public static final Orderdetails ORDERDETAILS = Orderdetails.ORDERDETAILS;

    /**
     * The table <code>classicmodels.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>classicmodels.payments</code>.
     */
    public static final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>classicmodels.productlines</code>.
     */
    public static final Productlines PRODUCTLINES = Productlines.PRODUCTLINES;

    /**
     * The table <code>classicmodels.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
