/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables.records;


import com.example.jooq.model.tables.Orders;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record7<Integer, Date, Date, Date, String, String, Integer> {

    private static final long serialVersionUID = 492323770;

    /**
     * Setter for <code>classicmodels.orders.orderNumber</code>.
     */
    public void setOrdernumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>classicmodels.orders.orderNumber</code>.
     */
    public Integer getOrdernumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>classicmodels.orders.orderDate</code>.
     */
    public void setOrderdate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>classicmodels.orders.orderDate</code>.
     */
    public Date getOrderdate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>classicmodels.orders.requiredDate</code>.
     */
    public void setRequireddate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>classicmodels.orders.requiredDate</code>.
     */
    public Date getRequireddate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>classicmodels.orders.shippedDate</code>.
     */
    public void setShippeddate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>classicmodels.orders.shippedDate</code>.
     */
    public Date getShippeddate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>classicmodels.orders.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>classicmodels.orders.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>classicmodels.orders.comments</code>.
     */
    public void setComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>classicmodels.orders.comments</code>.
     */
    public String getComments() {
        return (String) get(5);
    }

    /**
     * Setter for <code>classicmodels.orders.customerNumber</code>.
     */
    public void setCustomernumber(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>classicmodels.orders.customerNumber</code>.
     */
    public Integer getCustomernumber() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Date, Date, Date, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Date, Date, Date, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ORDERNUMBER;
    }

    @Override
    public Field<Date> field2() {
        return Orders.ORDERS.ORDERDATE;
    }

    @Override
    public Field<Date> field3() {
        return Orders.ORDERS.REQUIREDDATE;
    }

    @Override
    public Field<Date> field4() {
        return Orders.ORDERS.SHIPPEDDATE;
    }

    @Override
    public Field<String> field5() {
        return Orders.ORDERS.STATUS;
    }

    @Override
    public Field<String> field6() {
        return Orders.ORDERS.COMMENTS;
    }

    @Override
    public Field<Integer> field7() {
        return Orders.ORDERS.CUSTOMERNUMBER;
    }

    @Override
    public Integer component1() {
        return getOrdernumber();
    }

    @Override
    public Date component2() {
        return getOrderdate();
    }

    @Override
    public Date component3() {
        return getRequireddate();
    }

    @Override
    public Date component4() {
        return getShippeddate();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getComments();
    }

    @Override
    public Integer component7() {
        return getCustomernumber();
    }

    @Override
    public Integer value1() {
        return getOrdernumber();
    }

    @Override
    public Date value2() {
        return getOrderdate();
    }

    @Override
    public Date value3() {
        return getRequireddate();
    }

    @Override
    public Date value4() {
        return getShippeddate();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getComments();
    }

    @Override
    public Integer value7() {
        return getCustomernumber();
    }

    @Override
    public OrdersRecord value1(Integer value) {
        setOrdernumber(value);
        return this;
    }

    @Override
    public OrdersRecord value2(Date value) {
        setOrderdate(value);
        return this;
    }

    @Override
    public OrdersRecord value3(Date value) {
        setRequireddate(value);
        return this;
    }

    @Override
    public OrdersRecord value4(Date value) {
        setShippeddate(value);
        return this;
    }

    @Override
    public OrdersRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public OrdersRecord value6(String value) {
        setComments(value);
        return this;
    }

    @Override
    public OrdersRecord value7(Integer value) {
        setCustomernumber(value);
        return this;
    }

    @Override
    public OrdersRecord values(Integer value1, Date value2, Date value3, Date value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer ordernumber, Date orderdate, Date requireddate, Date shippeddate, String status, String comments, Integer customernumber) {
        super(Orders.ORDERS);

        set(0, ordernumber);
        set(1, orderdate);
        set(2, requireddate);
        set(3, shippeddate);
        set(4, status);
        set(5, comments);
        set(6, customernumber);
    }
}
