/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables.records;


import com.example.jooq.model.tables.Payments;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentsRecord extends UpdatableRecordImpl<PaymentsRecord> implements Record4<Integer, String, Date, BigDecimal> {

    private static final long serialVersionUID = 1637039367;

    /**
     * Setter for <code>classicmodels.payments.customerNumber</code>.
     */
    public void setCustomernumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>classicmodels.payments.customerNumber</code>.
     */
    public Integer getCustomernumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>classicmodels.payments.checkNumber</code>.
     */
    public void setChecknumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>classicmodels.payments.checkNumber</code>.
     */
    public String getChecknumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>classicmodels.payments.paymentDate</code>.
     */
    public void setPaymentdate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>classicmodels.payments.paymentDate</code>.
     */
    public Date getPaymentdate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>classicmodels.payments.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>classicmodels.payments.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Date, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Date, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Payments.PAYMENTS.CUSTOMERNUMBER;
    }

    @Override
    public Field<String> field2() {
        return Payments.PAYMENTS.CHECKNUMBER;
    }

    @Override
    public Field<Date> field3() {
        return Payments.PAYMENTS.PAYMENTDATE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Payments.PAYMENTS.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getCustomernumber();
    }

    @Override
    public String component2() {
        return getChecknumber();
    }

    @Override
    public Date component3() {
        return getPaymentdate();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getCustomernumber();
    }

    @Override
    public String value2() {
        return getChecknumber();
    }

    @Override
    public Date value3() {
        return getPaymentdate();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public PaymentsRecord value1(Integer value) {
        setCustomernumber(value);
        return this;
    }

    @Override
    public PaymentsRecord value2(String value) {
        setChecknumber(value);
        return this;
    }

    @Override
    public PaymentsRecord value3(Date value) {
        setPaymentdate(value);
        return this;
    }

    @Override
    public PaymentsRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public PaymentsRecord values(Integer value1, String value2, Date value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentsRecord
     */
    public PaymentsRecord() {
        super(Payments.PAYMENTS);
    }

    /**
     * Create a detached, initialised PaymentsRecord
     */
    public PaymentsRecord(Integer customernumber, String checknumber, Date paymentdate, BigDecimal amount) {
        super(Payments.PAYMENTS);

        set(0, customernumber);
        set(1, checknumber);
        set(2, paymentdate);
        set(3, amount);
    }
}
