/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables;


import com.example.jooq.model.Classicmodels;
import com.example.jooq.model.Indexes;
import com.example.jooq.model.Keys;
import com.example.jooq.model.tables.records.CustomersRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers extends TableImpl<CustomersRecord> {

    private static final long serialVersionUID = 1461234084;

    /**
     * The reference instance of <code>classicmodels.customers</code>
     */
    public static final Customers CUSTOMERS = new Customers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomersRecord> getRecordType() {
        return CustomersRecord.class;
    }

    /**
     * The column <code>classicmodels.customers.customerNumber</code>.
     */
    public final TableField<CustomersRecord, Integer> CUSTOMERNUMBER = createField(DSL.name("customerNumber"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.customerName</code>.
     */
    public final TableField<CustomersRecord, String> CUSTOMERNAME = createField(DSL.name("customerName"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.contactLastName</code>.
     */
    public final TableField<CustomersRecord, String> CONTACTLASTNAME = createField(DSL.name("contactLastName"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.contactFirstName</code>.
     */
    public final TableField<CustomersRecord, String> CONTACTFIRSTNAME = createField(DSL.name("contactFirstName"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.phone</code>.
     */
    public final TableField<CustomersRecord, String> PHONE = createField(DSL.name("phone"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.addressLine1</code>.
     */
    public final TableField<CustomersRecord, String> ADDRESSLINE1 = createField(DSL.name("addressLine1"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.addressLine2</code>.
     */
    public final TableField<CustomersRecord, String> ADDRESSLINE2 = createField(DSL.name("addressLine2"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>classicmodels.customers.city</code>.
     */
    public final TableField<CustomersRecord, String> CITY = createField(DSL.name("city"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.state</code>.
     */
    public final TableField<CustomersRecord, String> STATE = createField(DSL.name("state"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>classicmodels.customers.postalCode</code>.
     */
    public final TableField<CustomersRecord, String> POSTALCODE = createField(DSL.name("postalCode"), org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>classicmodels.customers.country</code>.
     */
    public final TableField<CustomersRecord, String> COUNTRY = createField(DSL.name("country"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.customers.salesRepEmployeeNumber</code>.
     */
    public final TableField<CustomersRecord, Integer> SALESREPEMPLOYEENUMBER = createField(DSL.name("salesRepEmployeeNumber"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>classicmodels.customers.creditLimit</code>.
     */
    public final TableField<CustomersRecord, BigDecimal> CREDITLIMIT = createField(DSL.name("creditLimit"), org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * Create a <code>classicmodels.customers</code> table reference
     */
    public Customers() {
        this(DSL.name("customers"), null);
    }

    /**
     * Create an aliased <code>classicmodels.customers</code> table reference
     */
    public Customers(String alias) {
        this(DSL.name(alias), CUSTOMERS);
    }

    /**
     * Create an aliased <code>classicmodels.customers</code> table reference
     */
    public Customers(Name alias) {
        this(alias, CUSTOMERS);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Customers(Table<O> child, ForeignKey<O, CustomersRecord> key) {
        super(child, key, CUSTOMERS);
    }

    @Override
    public Schema getSchema() {
        return Classicmodels.CLASSICMODELS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CUSTOMERS_PRIMARY, Indexes.CUSTOMERS_SALESREPEMPLOYEENUMBER);
    }

    @Override
    public UniqueKey<CustomersRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<CustomersRecord>> getKeys() {
        return Arrays.<UniqueKey<CustomersRecord>>asList(Keys.KEY_CUSTOMERS_PRIMARY);
    }

    @Override
    public List<ForeignKey<CustomersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CustomersRecord, ?>>asList(Keys.CUSTOMERS_IBFK_1);
    }

    public Employees employees() {
        return new Employees(this, Keys.CUSTOMERS_IBFK_1);
    }

    @Override
    public Customers as(String alias) {
        return new Customers(DSL.name(alias), this);
    }

    @Override
    public Customers as(Name alias) {
        return new Customers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(String name) {
        return new Customers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Name name) {
        return new Customers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, String, Integer, BigDecimal> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
