/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables;


import com.example.jooq.model.Classicmodels;
import com.example.jooq.model.Indexes;
import com.example.jooq.model.Keys;
import com.example.jooq.model.tables.records.OrderdetailsRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orderdetails extends TableImpl<OrderdetailsRecord> {

    private static final long serialVersionUID = 218120499;

    /**
     * The reference instance of <code>classicmodels.orderdetails</code>
     */
    public static final Orderdetails ORDERDETAILS = new Orderdetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderdetailsRecord> getRecordType() {
        return OrderdetailsRecord.class;
    }

    /**
     * The column <code>classicmodels.orderdetails.orderNumber</code>.
     */
    public final TableField<OrderdetailsRecord, Integer> ORDERNUMBER = createField(DSL.name("orderNumber"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>classicmodels.orderdetails.productCode</code>.
     */
    public final TableField<OrderdetailsRecord, String> PRODUCTCODE = createField(DSL.name("productCode"), org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>classicmodels.orderdetails.quantityOrdered</code>.
     */
    public final TableField<OrderdetailsRecord, Integer> QUANTITYORDERED = createField(DSL.name("quantityOrdered"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>classicmodels.orderdetails.priceEach</code>.
     */
    public final TableField<OrderdetailsRecord, BigDecimal> PRICEEACH = createField(DSL.name("priceEach"), org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>classicmodels.orderdetails.orderLineNumber</code>.
     */
    public final TableField<OrderdetailsRecord, Short> ORDERLINENUMBER = createField(DSL.name("orderLineNumber"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>classicmodels.orderdetails</code> table reference
     */
    public Orderdetails() {
        this(DSL.name("orderdetails"), null);
    }

    /**
     * Create an aliased <code>classicmodels.orderdetails</code> table reference
     */
    public Orderdetails(String alias) {
        this(DSL.name(alias), ORDERDETAILS);
    }

    /**
     * Create an aliased <code>classicmodels.orderdetails</code> table reference
     */
    public Orderdetails(Name alias) {
        this(alias, ORDERDETAILS);
    }

    private Orderdetails(Name alias, Table<OrderdetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Orderdetails(Name alias, Table<OrderdetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Orderdetails(Table<O> child, ForeignKey<O, OrderdetailsRecord> key) {
        super(child, key, ORDERDETAILS);
    }

    @Override
    public Schema getSchema() {
        return Classicmodels.CLASSICMODELS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDERDETAILS_PRIMARY, Indexes.ORDERDETAILS_PRODUCTCODE);
    }

    @Override
    public UniqueKey<OrderdetailsRecord> getPrimaryKey() {
        return Keys.KEY_ORDERDETAILS_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrderdetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderdetailsRecord>>asList(Keys.KEY_ORDERDETAILS_PRIMARY);
    }

    @Override
    public List<ForeignKey<OrderdetailsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderdetailsRecord, ?>>asList(Keys.ORDERDETAILS_IBFK_1, Keys.ORDERDETAILS_IBFK_2);
    }

    public Orders orders() {
        return new Orders(this, Keys.ORDERDETAILS_IBFK_1);
    }

    public Products products() {
        return new Products(this, Keys.ORDERDETAILS_IBFK_2);
    }

    @Override
    public Orderdetails as(String alias) {
        return new Orderdetails(DSL.name(alias), this);
    }

    @Override
    public Orderdetails as(Name alias) {
        return new Orderdetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderdetails rename(String name) {
        return new Orderdetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderdetails rename(Name name) {
        return new Orderdetails(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, BigDecimal, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
