/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables;


import com.example.jooq.model.Classicmodels;
import com.example.jooq.model.Indexes;
import com.example.jooq.model.Keys;
import com.example.jooq.model.tables.records.ProductlinesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productlines extends TableImpl<ProductlinesRecord> {

    private static final long serialVersionUID = 250219194;

    /**
     * The reference instance of <code>classicmodels.productlines</code>
     */
    public static final Productlines PRODUCTLINES = new Productlines();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductlinesRecord> getRecordType() {
        return ProductlinesRecord.class;
    }

    /**
     * The column <code>classicmodels.productlines.productLine</code>.
     */
    public final TableField<ProductlinesRecord, String> PRODUCTLINE = createField(DSL.name("productLine"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>classicmodels.productlines.textDescription</code>.
     */
    public final TableField<ProductlinesRecord, String> TEXTDESCRIPTION = createField(DSL.name("textDescription"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>classicmodels.productlines.htmlDescription</code>.
     */
    public final TableField<ProductlinesRecord, String> HTMLDESCRIPTION = createField(DSL.name("htmlDescription"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>classicmodels.productlines.image</code>.
     */
    public final TableField<ProductlinesRecord, byte[]> IMAGE = createField(DSL.name("image"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>classicmodels.productlines</code> table reference
     */
    public Productlines() {
        this(DSL.name("productlines"), null);
    }

    /**
     * Create an aliased <code>classicmodels.productlines</code> table reference
     */
    public Productlines(String alias) {
        this(DSL.name(alias), PRODUCTLINES);
    }

    /**
     * Create an aliased <code>classicmodels.productlines</code> table reference
     */
    public Productlines(Name alias) {
        this(alias, PRODUCTLINES);
    }

    private Productlines(Name alias, Table<ProductlinesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Productlines(Name alias, Table<ProductlinesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Productlines(Table<O> child, ForeignKey<O, ProductlinesRecord> key) {
        super(child, key, PRODUCTLINES);
    }

    @Override
    public Schema getSchema() {
        return Classicmodels.CLASSICMODELS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCTLINES_PRIMARY);
    }

    @Override
    public UniqueKey<ProductlinesRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCTLINES_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProductlinesRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductlinesRecord>>asList(Keys.KEY_PRODUCTLINES_PRIMARY);
    }

    @Override
    public Productlines as(String alias) {
        return new Productlines(DSL.name(alias), this);
    }

    @Override
    public Productlines as(Name alias) {
        return new Productlines(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Productlines rename(String name) {
        return new Productlines(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Productlines rename(Name name) {
        return new Productlines(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
